---ROLE
INSERT INTO "role" (name) VALUES ('POSTULANTE');
INSERT INTO "role" (name) VALUES ('ESCUELAS');
INSERT INTO "role" (name) VALUES ('REVISOR PRUEBAS');
INSERT INTO "role" (name) VALUES ('CALIFICADOR MÉRITOS');
INSERT INTO "role" (name) VALUES ('REVISOR IMPUGNACIÓN MERITOS');
INSERT INTO "role" (name) VALUES ('REVISOR PRESENTACIÓN PRÁCTICA');
INSERT INTO "role" (name) VALUES ('REVISOR IMPUGNACIÓN PRESENTACIÓN PRÁCTICA ');
INSERT INTO "role" (name) VALUES ('REVISOR APELACIONES');
INSERT INTO "role" (name) VALUES ('REVISOR ASIGNACIÓN DE CARGO');
INSERT INTO "role" (name) VALUES ('ARCHIVO');
INSERT INTO "role" (name) VALUES ('ADMINISTRADOR DGFM');
INSERT INTO "role" (name) VALUES ('JURIDICA');
INSERT INTO "role" (name) VALUES ('TRANSPARENCIA');
INSERT INTO "role" (name) VALUES ('SUPER ADMINISTRADOR');